#! /bin/sh

bspc config border_width        	2
bspc config window_gap          	8
bspc config split_ratio         	0.50
bspc config borderless_monocle  	false
bspc config gapless_monocle     	false
bspc config focus_by_distance 		true
bspc config adaptive_raise 		    true
bspc config normal_frame_opacity	0.01
bspc config focused_frame_opacity	1.00

# border colors
###############

# z-brah
bspc config focused_border_color	"#CEE318"
bspc config normal_border_color		"#4C4C4C"
bspc config active_border_color		"#CEE318"
bspc config presel_border_color		"#79CDCD"
bspc config urgent_border_color		"#79CDCD"

# zero
#bspc config focused_border_color	"#D17B49"
#bspc config normal_border_color		"#4A3637"
#bspc config active_border_color		"#D17B49"
#bspc config presel_border_color		"#6D715E"
#bspc config urgent_border_color		"#6D715E"

# nebula
#bspc config focused_border_color	"#14FFFF"
#bspc config normal_border_color		"#424242"
#bspc config active_border_color		"#14FFFF"
#bspc config presel_border_color		"#FFAF5F"
#bspc config urgent_border_color		"#FFAF5F"

# blackgum
#bspc config focused_border_color	"#AA0E50"
#bspc config normal_border_color		"#2E1F1F"
#bspc config active_border_color		"#AA0E50"
#bspc config presel_border_color		"#6DA3A1"
#bspc config urgent_border_color		"#6DA3A1"

# fresh
#bspc config focused_border_color	"#F5B915"
#bspc config normal_border_color		"#393939"
#bspc config active_border_color		"#F5B915"
#bspc config presel_border_color		"#00AFDA"
#bspc config urgent_border_color		"#00AFDA"

# erosion
#bspc config focused_border_color	"#9F7155"
#bspc config normal_border_color		"#332d29"
#bspc config active_border_color		"#9F7155"
#bspc config presel_border_color		"#FAFAC0"
#bspc config urgent_border_color		"#FAFAC0"

bspc config focus_follows_pointer	false

#bspc monitor -d 零 一 二 三
#bspc monitor -d endbahnhof netz plaudern referenz
#bspc monitor -d α β γ δ ε
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d i ii iii iv v
#bspc monitor -d ichi ni san yon go
#bspc monitor -d term web man 
#bspc monitor -d a s d f
#bspc monitor -d ° ° °
bspc monitor -d 1 2 3

bspc rule -a Firefox desktop=^2
bspc rule -a urxvt window=pseudo_tiled

PANEL_HEIGHT=14
PANEL_FIFO="/tmp/panel-fifo"
#PANEL_FONT="-*-neep-medium-r-semicondensed-*-11-*-*-*-*-*-*-*,-misc-fixed-medium-r-normal-ja-0-0-75-75-c-0-iso10646-1"
#PANEL_FONT="-*-tewi-*-r-normal-*-11-*-*-*-*-*-*-*"
PANEL_FONT="-*-gohufont-medium-*-*-11-*-*-*-*-*-*-1"

bspc config top_padding $PANEL_HEIGHT

#/home/rlee/scripts/pbar &
