#! /bin/sh

# . /home/rlee/scripts/panel_colors-bar

DARK="#FF666666"
LIGHT="#FFBBBBBB"

BATC="/sys/class/power_supply/BAT0/capacity"
BATS="/sys/class/power_supply/BAT0/status"

workspace(){
    SPACE_NUM=$(bspc query -D -d);
        case "$SPACE_NUM" in
            "1")
                WORKSPACE="%{F$LIGHT}●%{F-} %{F$DARK}● ●%{F-}";;
            "2")
                WORKSPACE="%{F$DARK}●%{F-} %{F$LIGHT}●%{F-} %{F$DARK}●%{F-}";;
            "3")
                WORKSPACE="%{F$DARK}● ●%{F-} %{F$LIGHT}●%{F-}";;
        esac
    echo -n $WORKSPACE
}

dat(){
	echo -n  $(date "+%H:%M")
}

mus(){
	echo -n  $(test -z "$(mpc current)" || mpc current -f %title%)
	#echo -n $(ps aux | grep -v "grep" | if grep -q "cmus"; then echo $(cmus-remote -Q | sed -n 's/tag title //p'); else echo "n/a"; fi)
}

vol(){
    echo -n $(amixer get PCM | grep "Front Left:" | awk '{print $5}')
}

wth(){
    #echo -n $(python2 ~/weather-cli/weathercli.py bicknell,in -u celsius --iconify)
    echo -n $(python2 ~/weather-cli/weathercli.py bicknell,in -u celsius | grep "It's" | awk '{print $2,$4,$5,$6}')
}

pause(){
    echo -n $(mpc | if grep -q "paused"; then echo -n "▎▎"; else echo -n "♫"; fi)
}

bat(){
    test "`cat $BATS`" = "Charging" && echo -n '+' || echo -n '-'
    sed -n p $BATC
}

while :; do
    printf "%s\n" "%{l} %{F$DARK}MPD:%{F-} $(pause) $(mus) %{F$DARK}VOL:%{F-} $(vol) %{c} $(workspace) %{r} %{F$DARK}BAT:%{F-} $(bat) %{F$DARK}WEATHER:%{F-} $(wth) %{F$DARK}TIME:%{F-} $(dat) "
#    printf "%s\n" "%{l} $(pause) $(mus) $(vol) %{c}$(workspace) %{r} $(wth) // $(dat) " 
#    printf "%s\n" "%{l} $(mus) $(vol) %{c} $(workspace) %{r} $(date) "
sleep 1
done	

#while read -r line ; do
#	case $line in
#		S*)
#			# clock output
#			sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#?}"
#			;;
#		T*)
#			# xtitle output
#			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}"
#			;;
#	    
#       	W*)
#			# bspwm internal state
#			wm_infos=""
#			IFS=':'
#			set -- ${line#?}
#			while [ $# -gt 0 ] ; do
#				item=$1
#				name=${item#?}
#				case $item in
#					O*)
#						# focused occupied desktop
#						wm_infos="$wm_infos %{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u}${name}%{-u}"
#						;;
#					F*)
#						# focused free desktop
#						wm_infos="$wm_infos %{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u}${name}%{-u}"
#						;;
#					U*)
#						# focused urgent desktop
#						wm_infos="$wm_infos %{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u}${name}%{-u}"
#						;;
#					o*)
#						# occupied desktop
#						wm_infos="$wm_infos %{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}${name}"
#						;;
#					f*)
#						# free desktop
#						wm_infos="$wm_infos %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}${name}"
#						;;
#					u*)
#						# urgent desktop
#						wm_infos="$wm_infos %{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}${name}"
#						;;
#					L*)
#						# layout
#						layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
#						wm_infos="$wm_infos %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG}$layout"
#						;;
#				esac
#				shift
#			done
#			;;
#	esac
#	printf "%s\n" " %{c} $wm_infos %{r} $sys_infos  "
#done
